name: Deploy Static Site to S3

on:
  push:
    branches:
      - main  # main branch par push hone par chalega

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Apni bucket ka region dalen

      # Step 3: Upload static files to S3
      - name: Upload to S3
        run: aws s3 sync . s3://clone-netflix3 --delete --exclude ".git/*" --exclude ".github/*"
